# Change these first
owner: natureoffice-gmbh # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: natureOffice 
    url: https://natureoffice.com/
  - name: ecozoom
    url: https://www.ecozoom.app/
  - name: direct.ecozoom.app (v2)
    url: https://direct.ecozoom.app/
    assignees:
      - kulturpessimist
  - name: direct-api.ecozoom.app (v2)
    url: https://direct-api.ecozoom.app/
    assignees:
      - kulturpessimist
  - name: natureBalance 5.x
    url: https://www.naturebalance.net/
    assignees:
      - kulturpessimist
  - name: Basic
    url: https://www.gemeinsam-ist-es-klimaschutz.de
  - name: nature.io (v1)
    url: https://www.nature.io/
    assignees:
      - kulturpessimist
  - name: Logokit
    url: https://lk.natureoffice.net/test
    __dangerous__body_down_if_text_missing: '"pass":true'
    assignees:
      - kulturpessimist
  - name: Puppet
    url: https://puppet.natureoffice.net/pdf?url=https://puppet.natureoffice.net
    assignees:
      - kulturpessimist
  - name: klimaneutral.me (v2)
    url: https://api-v2.klimaneutral.me
    assignees:
      - kulturpessimist
      
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.natureoffice.net
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: natureOffice Monitoring
  introTitle: "natureOffice infrastructure monitoring"
  introMessage: Collecting uptime and average response time of all customer facing systems.
  metaTags:
    - name: "robots"
      content: "noindex"
  navbar:
    - title: Status
      href: /
    #- title: GitHub
    #  href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
