# Change these first
owner: natureoffice-gmbh # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: ecozoom
    url: https://www.ecozoom.app/
  - name: next.nature.io (v2)
    url: https://next.nature.io/
    assignees:
      - kulturpessimist
  - name: api.nature.io (v2)
    url: https://api.nature.io/
    assignees:
      - kulturpessimist
  - name: natureBalance 5.x
    url: https://www.naturebalance.net/
    assignees:
      - kulturpessimist
  - name: Basic
    url: https://www.gemeinsam-ist-es-klimaschutz.de
  - name: nature.io (v1)
    url: https://www.nature.io/
    assignees:
      - kulturpessimist
  - name: Puppet
    url: https://puppet.natureoffice.net/pdf?url=https://puppet.natureoffice.net
    assignees:
      - kulturpessimist
      
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.natureoffice.net
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: natureOffice Uptime Monitor
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    #- title: GitHub
    #  href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
